### ISSUE TITLE
Setting up ROCM issue; ImportError: libhiprand.so.1 ; Specify CUDA_TOOLKIT_ROOT_DIR

### ISSUE THREAD

**Issue by wrightpt** [ROCmSoftwarePlatform/rocRAND#35]
I have AMD GPU. Trying to install ROCM to utilize tensorflow:

after installing ROCM. Python IDE provides the following:

ImportError: libhiprand.so.1: cannot open shared object file: No such file or directory

To solve this issue, I read i need to install RocRand to solve the issue but I get the following. I do not use Invidia GPU.

CMake Error at /usr/share/cmake-3.10/Modules/FindCUDA.cmake:682 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  cmake/SetupNVCC.cmake:72 (find_package)
  cmake/VerifyCompiler.cmake:28 (include)
  CMakeLists.txt:49 (include)

-- Configuring incomplete, errors occurred!
See also "/home/c/Downloads/rocRAND-master/build/CMakeFiles/CMakeOutput.log".

When I run "hipconfig":  bash: hipconfig: command not found

**Comment by jlgreathouse** [comment]
What OS are you running, and what process are you following to install ROCm, MIOpen, Tensorflow, and rocRAND?

**Comment by wrightpt** [comment]
Ubuntu 18.04.

Initially, I followed the process outlined steps here (https://rocm.github.io/ROCmInstall.html):

> Ubuntu Support - installing from a Debian repository
> First make sure your system is up to date
> sudo apt update
> sudo apt dist-upgrade
> sudo apt install libnuma-dev
> sudo reboot
> Add the ROCm apt repository
> For Debian based systems, like Ubuntu, configure the Debian ROCm repository as follows:
> 
> wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -
> echo 'deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main' | sudo tee /etc/apt/sources.list.d/rocm.list
> The gpg key might change, so it may need to be updated when installing a new release. If the key signature verification fails when you attempt to update, please re-add the key from ROCm apt repository. The current rocm.gpg.key is not avialable in a standard key ring distribution, but has the following sha1sum hash:
> 
> f7f8147431c75e505c58a6f3a3548510869357a6 rocm.gpg.key
> 
> Install
> Next, update the apt repository list and install the ROCm package:
> 
> Warning: Before proceeding, make sure to completely uninstall any previous ROCm package:
> 
> sudo apt update
> sudo apt install rocm-dkms

Then i did the following from Tensorflow upstream (https://github.com/ROCmSoftwarePlatform/tensorflow-upstream):

> # Install some ROCm dependencies
> sudo apt install rocm-libs miopen-hip cxlactivitylogger
> 
> # Pip3 install the whl package from PyPI
> pip3 install --user tensorflow-rocm

**Comment by wrightpt** [comment]
I do not recall installing MIopen

**Comment by wrightpt** [comment]
I reinstalled everything.

```
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

```

> /usr/bin/python3.5 /home/c/.PyCharmCE2018.2/config/scratches/scratch.py
> Traceback (most recent call last):
>   File "/home/c/.PyCharmCE2018.2/config/scratches/scratch.py", line 1, in <module>
>     import tensorflow as tf
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/__init__.py", line 22, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 81, in <module>
>     from tensorflow.python import keras
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/keras/__init__.py", line 24, in <module>
>     from tensorflow.python.keras import activations
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/keras/activations/__init__.py", line 22, in <module>
>     from tensorflow.python.keras._impl.keras.activations import elu
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/__init__.py", line 21, in <module>
>     from tensorflow.python.keras._impl.keras import activations
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/activations.py", line 24, in <module>
>     from tensorflow.python.keras._impl.keras.utils.generic_utils import deserialize_keras_object
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/utils/__init__.py", line 34, in <module>
>     from tensorflow.python.keras._impl.keras.utils.multi_gpu_utils import multi_gpu_model
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/utils/multi_gpu_utils.py", line 22, in <module>
>     from tensorflow.python.keras._impl.keras.engine.training import Model
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/__init__.py", line 21, in <module>
>     from tensorflow.python.keras._impl.keras.engine.base_layer import InputSpec
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 28, in <module>
>     from tensorflow.python.estimator import util as estimator_util
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/estimator/__init__.py", line 25, in <module>
>     import tensorflow.python.estimator.estimator_lib
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator_lib.py", line 22, in <module>
>     from tensorflow.python.estimator.canned.baseline import BaselineClassifier
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/estimator/canned/baseline.py", line 50, in <module>
>     from tensorflow.python.estimator import estimator
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 34, in <module>
>     from tensorflow.python.estimator import model_fn as model_fn_lib
>   File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/estimator/model_fn.py", line 29, in <module>
>     from tensorflow.python.keras.metrics import Metric
> ImportError: cannot import name 'Metric'
